services:
  - type: web
    name: my-upscaler
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      bash install_esrgan.sh
    startCommand: "gunicorn -w 2 -t 120 -b 0.0.0.0:10000 app:app"
    envVars:
      - key: PORT
        value: 10000
